title: ASIC Design
description: All things related to ASIC Design
theme: just-the-docs

url: https://akiitr.github.io/asic

aux_links:
  Template Repository: https://akiitr.github.io/asic

# Mermaid: for flow charts
mermaid:
  # Version of mermaid library
  # Pick an available version from https://cdn.jsdelivr.net/npm/mermaid/
  version: "11.4.1"